GOODS_NAME = [ ... % from http://www.worldstopexports.com/worlds-top-export-products/
  'machinery', ...
  'fuels', ...
  'vehicles', ...
  'plastics', ...
  'gems', ...
  'steel', ...
  'chemicals', ...
  'aircraft', ...
  'Furniture', ...
  'Clothing', ...
  'Aluminum', ...
  'Rubber', ...
  'Paper', ...
]';
assert(length(GOODS_NAME) >= N_GOOD);
