hold off;
plot(sum_r_history);
hold on;
% plot(capital_GDP_history);
plot(consumer_GDP_history);
plot(structural_change_history * 10 + 1)
area(p_history);
legend( ...
  'r', ...
  'consumer GDP', ...
  'Structural Change', ...
  'Prices' ...
);
  % 'capital GDP', ...
