LINEWIDTH = 1.5;
SHIFT = 3;

hold off;
plot(sum_r_history + SHIFT, 'linewidth', LINEWIDTH);
hold on;
plot(capital_GDP_history + SHIFT, 'linewidth', LINEWIDTH);
plot(consumer_GDP_history + SHIFT, 'linewidth', LINEWIDTH);
plot(structural_change_history * 10 + 1, 'linewidth', LINEWIDTH)
area(p_history);
legend( ...
  'r', ...
  'capital GDP', ...
  'consumer GDP', ...
  'Structural Change', ...
  'Prices' ...
);
axis([0 length(sum_r_history) 0 6]);
